export const courseData = [
    {
        id: null,
        name: 'JavaScript Intermediate',
        alias: 'javascript-intermediate',
        description:
            'Have you already mastered the basics of JavaScript, and want to expand your knowledge? Then you’re in the right place. This course will teach you how to make more complex and flexible programs as well as even more interactive websites. This course follows our Introduction to Javascript course. We recommend you take a quick look at what’s covered there before you start this course.',
        typeId: 1,
        enrollmentStatusId: 1,
        progressionStatusId: 1,
        levelId: 2,
        bundle: null,
        orderNumber: 1,
        lastActivityDate: '2023-03-10T05:52:24',
        uiConfigurations: {
            iconUrl:
                'https://sllearnengine.blob.core.windows.net/material-images/5b23e931b0c74a1ab22de5cff2531bff-JV_2.png',
            color: '#FFF2A1',
        },
        categoryIds: [1],
        isTop: false,
        progress: null,
    },
    {
        id: null,
        name: 'Introduction to Python',
        alias: 'python-introduction',
        description:
            'Python is a popular, easy-to-learn, and very powerful programming language, which is used in software and web development, data science, machine learning, and many other fields. In this course, we’ll cover the basic concepts of Python, as well as build real-life projects and solve different coding challenges. Python for Beginners requires no prior programming experience, so let’s dive right in!',
        typeId: 1,
        enrollmentStatusId: 1,
        progressionStatusId: 1,
        levelId: 1,
        bundle: null,
        orderNumber: 2,
        lastActivityDate: '2023-03-06T04:55:11',
        uiConfigurations: {
            iconUrl:
                'https://sllearnengine.blob.core.windows.net/material-images/d7aa9e6be90c47c3968f99d1a30792e1-Python For Beginners.png',
            color: '#3770A0',
        },
        categoryIds: [4, 5],
        isTop: true,
        progress: null,
    },
    {
        id: 1014,
        name: 'HTML',
        alias: 'HTML',
        description:
            'This FREE course will teach you how to design a web page using HTML. Complete a series of hands-on exercises and practice while writing real HTML code.',
        typeId: 10,
        enrollmentStatusId: 1,
        progressionStatusId: 2,
        levelId: 1,
        bundle: null,
        orderNumber: 3,
        lastActivityDate: '2022-07-16T13:40:07',
        uiConfigurations: {
            iconUrl: 'https://uploads.sololearn.com/uploads/courses/1014.png',
            color: '#FF9F73',
        },
        categoryIds: [1],
        isTop: false,
        progress: 1.0,
    },
    {
        id: 1097,
        name: 'React + Redux',
        alias: 'react',
        description:
            'Learn to build powerful interactive user interfaces using a popular JavaScript library trusted by Facebook and Uber. Dive into the core concepts of React and Redux.',
        typeId: 10,
        enrollmentStatusId: 1,
        progressionStatusId: 1,
        levelId: 3,
        bundle: null,
        orderNumber: 4,
        lastActivityDate: '2022-04-28T03:20:57',
        uiConfigurations: {
            iconUrl: 'https://uploads.sololearn.com/uploads/courses/1097.png',
            color: '#4DC6FF',
        },
        categoryIds: [1],
        isTop: false,
        progress: 0.260869565217,
    },
    {
        id: 1023,
        name: 'CSS',
        alias: 'CSS',
        description:
            'Our CSS course will teach you how to control the style & layout of websites. Complete a series of exercises and practice while filling out actual CSS templates.',
        typeId: 10,
        enrollmentStatusId: 1,
        progressionStatusId: 2,
        levelId: 1,
        bundle: null,
        orderNumber: 5,
        lastActivityDate: '2021-09-11T16:35:26',
        uiConfigurations: {
            iconUrl: 'https://uploads.sololearn.com/uploads/courses/1023.png',
            color: '#74D5FC',
        },
        categoryIds: [1],
        isTop: false,
        progress: 1.0,
    },
    {
        id: 1068,
        name: 'Java',
        alias: 'Java',
        description:
            'With our interactive Java course, you’ll learn object-oriented Java programming and have the ability to write clear and valid code in almost no time at all.',
        typeId: 10,
        enrollmentStatusId: 1,
        progressionStatusId: 1,
        levelId: 1,
        bundle: null,
        orderNumber: 6,
        lastActivityDate: '2021-03-28T12:25:52',
        uiConfigurations: {
            iconUrl: 'https://uploads.sololearn.com/uploads/courses/1068.png',
            color: '#FFBE70',
        },
        categoryIds: [2, 3, 4],
        isTop: false,
        progress: 0.028169014084,
    },

];
